services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      NODE_FUNCTION_ALLOW_BUILTIN: crypto
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      GENERIC_TIMEZONE: Asia/Tokyo
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      WEBHOOK_URL: https://${SUBDOMAIN}.${DOMAIN_NAME}/
    volumes:
      - n8n_data:/home/node/.n8n

  cf:
    image: cloudflare/cloudflared:latest
    container_name: cf
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    depends_on:
      - n8n

volumes:
  n8n_data:
